# Generated by Django 4.1.6 on 2023-02-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dpi',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.pais'),
        ),
    ]
