# Generated by Django 4.1.6 on 2023-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_persona_dpi_persona_nacimiento_persona_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
