# Generated by Django 4.1.6 on 2023-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_pais_options_evento_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.IntegerField(choices=[('1', 'No puedo hacer Entrar'), ('2', 'No aparece mi Evento'), ('3', 'Otros')])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
